### ISSUE TITLE
Power supply 

### ISSUE THREAD

**Issue by narkisg** [OLIMEX/OLIMEXINO-STM32F3#5]
The Power supply is only working from 12VDC to 16.3VDC
any reason why?

**Comment by DanKoloff** [comment]
Where do you apply the power? Are you using the barrel jack?

**Comment by narkisg** [comment]
Good for you to remember....
since then, your company admit that the boards had fault in components and change the BOM.

**Comment by DanKoloff** [comment]
I don't see any changes related to the powering circuit. Maybe I am wrong. The changes are see are cosmetic (labels change, white print changes, etc). Can you provide any proof that our "company admit that the boards had fault in components and change the BOM"?
